version: '2'
services:
    csvserver:
        image: infracloudio/csvserver:latest
        ports:
            - 9393:9300
        volumes:
            - /home/cloud_user/csvserver_solution/solution/inputFile:/csvserver/inputdata
        environment:
            CSVSERVER_BORDER: Orange
